package VisualizzaFSE;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class FSEDialog {

    private FSEControl control;
    private String content;
    private JButton stampaButton;
    private JPanel panel;
    private JTextArea textArea1;

    public FSEDialog(FSEControl control, String content, boolean canPrint) {
        this.control = control;
        this.content = content;

        JFrame frame = new JFrame("SPRINT - Fascicolo Sanitario Elettronico");
        $$$setupUI$$$();
        frame.setContentPane(panel);
        frame.setLocationRelativeTo(null);

        textArea1.setEditable(false);
        textArea1.setLineWrap(true);
        textArea1.setWrapStyleWord(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        if (!canPrint) {
            stampaButton.setEnabled(false);
            stampaButton.setToolTipText("Per stampare la cartella clinica è necessario rivolgersi al personale e pagare la marca da bollo");
        }
        textArea1.append(content);

        frame.pack();
        frame.setVisible(true);
        stampaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                stampaFSE();
            }
        });
    }

    public void stampaFSE() {
        control.stampa();
    }

    public void storicoVisite() {

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        stampaButton = new JButton();
        stampaButton.setText("Stampa");
        panel.add(stampaButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_EAST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setVerticalScrollBarPolicy(22);
        panel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(500, 10), null, null, 0, false));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(1, 1, 1, 1), null));
        textArea1 = new JTextArea();
        textArea1.setAutoscrolls(false);
        textArea1.setEditable(false);
        textArea1.setText("");
        scrollPane1.setViewportView(textArea1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
