title: "Sviluppo del software"
description: "Repository per la tesina di Basi di Dati e Sviluppo del Software"
#theme: jekyll-theme-slate
remote_theme: ggentili/Italia-Design-Jekyll-Theme
permalink: /404.md
show_downloads: true
